default:
  tags:
    - clubmap

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - chmod +x ./buildImage.sh && chmod +x ./pushImage.sh
    - chmod +x ./backend/buildImage.sh && chmod +x ./backend/pushImage.sh
    - chmod +x ./frontend/buildImage.sh && chmod +x ./frontend/pushImage.sh
    - ./buildImage.sh
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - ./pushImage.sh
  only:
    - master


deploy_on_stend:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod +x ./down-dev.sh && chmod +x ./up-dev.sh
    - ./down-dev.sh
  script:
    - ./up-dev.sh
  only:
    - master
