version: '3.7'

services:

  backend:
    image: registry.gitlab.com/club-map/main/backend:latest
    ports:
      - 8080:8080
    networks:
      mp:
    restart: unless-stopped

  frontend:
    image: registry.gitlab.com/club-map/main/frontend:latest
    volumes:
      - ../frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      mp:
    restart: unless-stopped

networks:
  mp:
