version: '3.7'

services:

  backend:
    image: registry.gitlab.com/club-map/main/backend:latest
    ports:
      - 8080:8080
    networks:
      mp:
    restart: unless-stopped

  frontend:
    image: registry.gitlab.com/club-map/main/frontend:latest
    volumes:
      - ../frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      mp:
    restart: unless-stopped

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clubmap
    networks:
      mp:
    ports:
      - 5432:5432

networks:
  mp:
